#!/usr/bin/env bash
# Bring the game up end-to-end: server → Cloudflare tunnel → QR code + LINKS.md.
#
#   ./infra/start.sh             start whatever isn't running; if everything is
#                                already up and healthy, report that and stop
#
#   LAVA_RESTART_OK=1 ./infra/start.sh --restart
#                                stop server + tunnel and bring both up fresh.
#                                Gated behind the env var because it changes the
#                                iPad URL — human-requested only, never routine.
#
# Safe to run any time — it never breaks a healthy setup.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root: game code in game/, infra artifacts in infra/

PORT=8080
TOOLS=infra/.tools
CLOUDFLARED=$TOOLS/cloudflared
LOG=$TOOLS/cloudflared.log
QR=game-starter-QR.png

RESTART=false
if [ "${1:-}" = "--restart" ]; then
  if [ "${LAVA_RESTART_OK:-}" != "1" ]; then
    echo "✗ --restart refused: it kills the tunnel and changes the iPad URL." >&2
    echo "  This is for humans only. If the user explicitly asked for a restart, they" >&2
    echo "  (or you, on their explicit request) can run:" >&2
    echo "      LAVA_RESTART_OK=1 ./infra/start.sh --restart" >&2
    echo "  For everything else, plain ./infra/start.sh already fixes what's down" >&2
    echo "  without changing the URL." >&2
    exit 1
  fi
  RESTART=true
elif [ -n "${1:-}" ]; then
  echo "Usage: $0 [--restart]  (restart additionally requires LAVA_RESTART_OK=1)" >&2
  exit 1
fi

server_up() { curl -sf "http://localhost:$PORT/config" >/dev/null 2>&1; }

tunnel_url() { grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' "$LOG" 2>/dev/null | head -1 || true; }

tunnel_process_up() { pgrep -f "cloudflared tunnel" >/dev/null 2>&1; }

serving_externally() {  # $1 = tunnel URL
  [ "$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$1/" || true)" = "200" ]
}

write_links() {  # $1 = tunnel URL
  npx --yes qrcode "$1/" -o "$QR" >/dev/null 2>&1
  # LINKS.md is the one place to find the current URLs. Regenerated whenever the
  # tunnel URL changes: it's random per run and differs between codespace
  # instances, so never trust a stale copy (gitignored).
  cat > LINKS.md <<EOF
# Current links (regenerated by start.sh — do not edit)

Generated: $(date -u '+%Y-%m-%d %H:%M UTC')

| What | URL |
|---|---|
| Game (iPad) | $1/ |
| Dev panel | $1/dev.html |
| Sound lab | $1/sound.html |
| Game (local) | http://localhost:$PORT/ |
| Dev panel (local) | http://localhost:$PORT/dev.html |

QR for the iPad camera: \`$QR\` (also fresh each start).
If any link 404s or times out, re-run \`./infra/start.sh\` and use the new ones.
EOF
}

report() {  # $1 = tunnel URL, $2 = status line
  echo "$2"
  echo "  Game (iPad): $1/"
  echo "  Dev panel:   $1/dev.html"
  echo "  QR code:     $QR  ·  all links: LINKS.md"
}

# ── 0. Already fully up and healthy? Report and stop (unless --restart). ──
if $RESTART; then
  echo "Restarting everything (--restart)..."
  pkill -f "node game/server.js" 2>/dev/null || true
  pkill -f "cloudflared tunnel" 2>/dev/null || true
  sleep 0.5
elif server_up; then
  URL=$(tunnel_url)
  if [ -n "$URL" ] && tunnel_process_up && serving_externally "$URL"; then
    # Make sure LINKS.md/QR match the live tunnel before declaring victory
    grep -qF "$URL" LINKS.md 2>/dev/null || write_links "$URL"
    report "$URL" "✓ everything already running and healthy — nothing to do"
    exit 0
  fi
fi

# ── 1. Game server (leave it alone if already up) ──
if ! server_up; then
  echo "Starting game server..."
  nohup node game/server.js > infra/server.log 2>&1 &
  for _ in $(seq 1 20); do
    server_up && break
    sleep 0.5
  done
fi
server_up || { echo "✗ server failed to start — see infra/server.log"; exit 1; }
echo "✓ server running on :$PORT"

# ── 2. cloudflared binary (downloaded once, kept in .tools/) ──
mkdir -p "$TOOLS"
if [ ! -x "$CLOUDFLARED" ]; then
  echo "Downloading cloudflared (one-time)..."
  curl -sL -o "$CLOUDFLARED" https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
  chmod +x "$CLOUDFLARED"
fi

# ── 3. Tunnel: reuse a live one, otherwise start fresh (URL is random per start) ──
URL=$(tunnel_url)
if tunnel_process_up && [ -n "$URL" ] && serving_externally "$URL"; then
  echo "✓ reusing existing tunnel: $URL"
else
  pkill -f "cloudflared tunnel" 2>/dev/null || true
  sleep 0.5
  nohup "$CLOUDFLARED" tunnel --url "http://localhost:$PORT" > "$LOG" 2>&1 &
  echo "Starting tunnel..."
  URL=""
  for _ in $(seq 1 40); do
    URL=$(tunnel_url)
    [ -n "$URL" ] && break
    sleep 0.5
  done
  [ -n "$URL" ] || { echo "✗ tunnel failed to start — see $LOG"; exit 1; }

  # Verify the game is actually reachable from outside
  # (fresh tunnel hostnames can take up to a minute to appear in DNS)
  OK=false
  for _ in $(seq 1 60); do
    serving_externally "$URL" && { OK=true; break; }
    sleep 1
  done
  $OK || { echo "✗ tunnel up but hostname not serving after 60s — DNS for fresh"
           echo "  trycloudflare hostnames is sometimes slow; re-run ./infra/start.sh"
           echo "  to roll a new hostname."; exit 1; }
  echo "✓ tunnel verified: $URL"
fi

# ── 4. QR + LINKS.md, kept in sync with the live URL ──
grep -qF "$URL" LINKS.md 2>/dev/null || write_links "$URL"
report "$URL" "✓ up and verified end-to-end"
echo ""
echo "  Open $QR and scan it with the iPad camera."
